### ISSUE TITLE
Add support for timeout installing plugins

### ISSUE THREAD

**Issue by prabjohns-atex** [karlmdavis/ansible-role-jenkins2#42]
jenkins_plugin supports a timeout, which is sometimes necessary if the plugin install is slow.

`failed: [QAE-BND-001] (item=workflow-aggregator) => {"changed": false, "details": "Connection failure: timed out", "item": "workflow-aggregator", "msg": "Cannot install plugin."}
`
Changed plugins.yml to be:

```
- name: Install Plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
    jenkins_home: "{{ jenkins_home }}"
    url: "{{ jenkins_url_local }}"
    params:
      url_username: "{{ jenkins_dynamic_admin_username | default(omit) }}"
    url_password: "{{ jenkins_dynamic_admin_password | default(omit) }}"
    validate_certs: "{{ false if ansible_distribution_release == 'trusty' else true }}"
    timeout: 120
  with_items:
    - "{{ jenkins_plugins_recommended }}"
    - "{{ jenkins_plugins_extra }}"
  become: true
  notify:
    - "Restart Service 'jenkins'"

- name: Update Plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: latest
    jenkins_home: "{{ jenkins_home }}"
    url: "{{ jenkins_url_local }}"
    params:
      url_username: "{{ jenkins_dynamic_admin_username | default(omit) }}"
    url_password: "{{ jenkins_dynamic_admin_password | default(omit) }}"
    validate_certs: "{{ false if ansible_distribution_release == 'trusty' else true }}"
    timeout: 120
  with_items:
    - "{{ jenkins_plugins_recommended }}"
    - "{{ jenkins_plugins_extra }}"
  become: true
  notify:
    - "Restart Service 'jenkins'"
```
